version: '3'

services:
    db:
        container_name: db-container
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=application
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - application
        ports:
            - '8004:5432'
        volumes: 
            - ./db/init.sql:/var/lib/postgresql/data
            
    website:
        container_name: website-container
        build:
            context: php-apache
        volumes:
            - ../website:/var/www/html
        networks:
            - application
        depends_on:
            - db
        restart: always
        ports:
            - '8000:80'

    api:
        container_name: api-container
        build:
            context: php-apache
        volumes:
            - ../api:/var/www/html
        networks:
            - application
        depends_on:
            - db
        restart: always
        ports:
            - '9000:80'
    
    elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        networks:
            - application
        depends_on:
            - website
            - api
        restart: always
        ports:
            - '9200:9200'

    kibana:
        container_name: kb-container
        image: docker.elastic.co/kibana/kibana:7.7.0
        environment:
            - ELASTICSEARCH_HOSTS=http://es-container:9200
        networks:
            - application
        depends_on:
            - elasticsearch
        restart: always
        ports:
            - '5601:5601'
    
volumes:
  db:
    driver: local

networks:
  application:
    driver: bridge